FROM wordpress:php8.4-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN pecl install redis \
    && docker-php-ext-enable redis


COPY ./upload.ini /usr/local/etc/php/conf.d
COPY ./cache.ini /usr/local/etc/php/conf.d
