name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build-legacy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: wp-php-pdo # Provide only Docker image name, tag will be automatically set to latest
          image-tag: legacy
          dockerfile: Dockerfile-legacy
  build-current:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: wp-php-pdo # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: Dockerfile-latest
